### ISSUE TITLE
System support for deferring work to be done on next execute

### ISSUE THREAD

**Issue by spendo-atl** [LastOliveGames/becsy#10]
This is a question to ask if you would consider a contribution of this kind?

Currently we have a lot of input Systems which listen for events and read/write Entities when an event is emitted (e.g. onMouseDown do x, y, z...). When an event is emitted; naively, anything done in the listener callback is done immediately and not within the systems `execute` which I've come to understand is undesirable.

We have been setting up ways in our Systems to store operations (for example in a field called `pendingUpdates` which is drained in `execute`) with the goal of reading/writing Entities during `execute` cycles only. This is relatively easy with some abstraction.

I was wondering if you'd consider supporting such a thing in Systems by default?

This could be achieved for instance by providing a new function `this.doNext(fn)` in the System base class which stores callbacks to be run and cleared during the next Systems execute.

**Comment by pkaminski** [comment]
Coroutines are now implemented in 0.9.3.  You don't even need to `yield` first since a coroutine will only run when its system is executing, even if it's started from somewhere / sometime else.  (Though I guess you still need at least one `yield` in there somewhere to make it a generator...)

However, note that execution order of coroutines is not guaranteed, and will in fact tend to be in reverse order of being started, so this might not be a good fit for event processing after all.
