### ISSUE TITLE
Question: Enumerating all active components on an entity

### ISSUE THREAD

**Issue by rubybrowncoat** [LastOliveGames/becsy#28]
I'm wondering if there's a built it way to enumerate the currently active components on an entity for either logging/debugging purposes or other general access to the component types, not necessarily to read current component data on the entity itself.

What I'm doing temporarily is something like the following:
```typescript
entity.__registry.types.flatMap((type) => {
  const binding = type.__binding!
  const index = entity.__id * entity.__registry.shapes.stride + binding.shapeOffset
      
  return entity.__registry.shapes.array[index] & binding.shapeMask ? [type.name] : []
})
```

But `__registry` isn't "actually" accessible on the entity impl, so I am bypassing type-checking and forcing.
I'm looking for a different approach, if it exists.

**Comment by pkaminski** [comment]
There's nothing built in but it's not too hard to put it together yourself.  First, you can replace all the nasty array-wrangling code with:

```
entity.__registry.types.filter(type => entity.has(type)).map(type => type.name);
```

This leaves the question of how to get a list of all component types.  I wouldn't recommend using `entity.__registry.types`, not just because it's private but also because it'll have an extra synthetic component type in it (and possibly more in the future).  Instead, you can populate your own list from the `defs` you pass to `World.create` — chances are, you make a list of app component types at that point anyway.

If your intention is to make an app-independent debugging tool then the entry point you're looking for is `world.stats`.  This has a `world.stats.components` object that maps component type names to some basic stats, which include a `type` property.  So you can do:

```
Object.values(world.stats.components).map(stat => stat.type).filter(type => entity.has(type)).map(type => type.name);
```

Note that currently stats are included in both the debug and performance builds, but it's possible that in the future there'll be builds where they're not included.

Hope this helps!

**Comment by rubybrowncoat** [comment]
Thanks for the help, I didn't realize `world.stats` had systems and components which is great. Cheers
